size: 25
Traceback (most recent call last):
  File "measurements.py", line 157, in <module>
    main()
  File "measurements.py", line 135, in main
    measurements.naive_pocl_measurements()
  File "measurements.py", line 58, in naive_pocl_measurements
    results = self._measure(self.naive_pocl)
  File "measurements.py", line 102, in _measure
    obj.all_matches(paterns[i])
  File "/gpfs/hpchome/andriiro/seminar/pattern_matching/Pyopencl/naive/naive_pocl.py", line 51, in all_matches
    search(queue, (self.text_len, ), 256, d_str, d_pat, self.text_len, len(pattern), d_matches)
  File "/gpfs/hpchome/andriiro/.local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 509, in kernel_call
    self.set_args(*args)
  File "/gpfs/hpchome/andriiro/.local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 562, in kernel_set_args
    % (i+1, str(e), advice))
pyopencl.LogicError: when processing argument #3 (1-based): clSetKernelArg failed: invalid arg size
size: 25
Traceback (most recent call last):
  File "measurements.py", line 157, in <module>
    main()
  File "measurements.py", line 135, in main
    measurements.naive_pocl_measurements()
  File "measurements.py", line 58, in naive_pocl_measurements
    results = self._measure(self.naive_pocl)
  File "measurements.py", line 102, in _measure
    obj.all_matches(paterns[i])
  File "/gpfs/hpchome/andriiro/seminar/pattern_matching/Pyopencl/naive/naive_pocl.py", line 51, in all_matches
    search(queue, (self.text_len, ), 256, d_str, d_pat, self.text_len, len(pattern), d_matches)
  File "/gpfs/hpchome/andriiro/.local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 509, in kernel_call
    self.set_args(*args)
  File "/gpfs/hpchome/andriiro/.local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 562, in kernel_set_args
    % (i+1, str(e), advice))
pyopencl.LogicError: when processing argument #3 (1-based): clSetKernelArg failed: invalid arg size
size: 25
Traceback (most recent call last):
  File "measurements.py", line 157, in <module>
    main()
  File "measurements.py", line 135, in main
    measurements.naive_pocl_measurements()
  File "measurements.py", line 58, in naive_pocl_measurements
    results = self._measure(self.naive_pocl)
  File "measurements.py", line 102, in _measure
    obj.all_matches(paterns[i])
  File "/gpfs/hpchome/andriiro/seminar/pattern_matching/Pyopencl/naive/naive_pocl.py", line 51, in all_matches
    search(queue, (self.text_len, ), 256, d_str, d_pat, self.text_len, len(pattern), d_matches)
  File "/gpfs/hpchome/andriiro/.local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 509, in kernel_call
    self.set_args(*args)
  File "/gpfs/hpchome/andriiro/.local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 562, in kernel_set_args
    % (i+1, str(e), advice))
pyopencl.LogicError: when processing argument #3 (1-based): clSetKernelArg failed: invalid arg size
srun: error: stage4: tasks 4-5,9: Exited with exit code 1
size: 25
Traceback (most recent call last):
  File "measurements.py", line 157, in <module>
    main()
  File "measurements.py", line 135, in main
    measurements.naive_pocl_measurements()
  File "measurements.py", line 58, in naive_pocl_measurements
    results = self._measure(self.naive_pocl)
  File "measurements.py", line 102, in _measure
    obj.all_matches(paterns[i])
  File "/gpfs/hpchome/andriiro/seminar/pattern_matching/Pyopencl/naive/naive_pocl.py", line 51, in all_matches
    search(queue, (self.text_len, ), 256, d_str, d_pat, self.text_len, len(pattern), d_matches)
  File "/gpfs/hpchome/andriiro/.local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 509, in kernel_call
    self.set_args(*args)
  File "/gpfs/hpchome/andriiro/.local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 562, in kernel_set_args
    % (i+1, str(e), advice))
pyopencl.LogicError: when processing argument #3 (1-based): clSetKernelArg failed: invalid arg size
size: 25
Traceback (most recent call last):
  File "measurements.py", line 157, in <module>
    main()
  File "measurements.py", line 135, in main
    measurements.naive_pocl_measurements()
  File "measurements.py", line 58, in naive_pocl_measurements
    results = self._measure(self.naive_pocl)
  File "measurements.py", line 102, in _measure
    obj.all_matches(paterns[i])
  File "/gpfs/hpchome/andriiro/seminar/pattern_matching/Pyopencl/naive/naive_pocl.py", line 51, in all_matches
    search(queue, (self.text_len, ), 256, d_str, d_pat, self.text_len, len(pattern), d_matches)
  File "/gpfs/hpchome/andriiro/.local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 509, in kernel_call
    self.set_args(*args)
  File "/gpfs/hpchome/andriiro/.local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 562, in kernel_set_args
    % (i+1, str(e), advice))
pyopencl.LogicError: when processing argument #3 (1-based): clSetKernelArg failed: invalid arg size
size: 25
Traceback (most recent call last):
  File "measurements.py", line 157, in <module>
    main()
  File "measurements.py", line 135, in main
    measurements.naive_pocl_measurements()
  File "measurements.py", line 58, in naive_pocl_measurements
    results = self._measure(self.naive_pocl)
  File "measurements.py", line 102, in _measure
    obj.all_matches(paterns[i])
  File "/gpfs/hpchome/andriiro/seminar/pattern_matching/Pyopencl/naive/naive_pocl.py", line 51, in all_matches
    search(queue, (self.text_len, ), 256, d_str, d_pat, self.text_len, len(pattern), d_matches)
  File "/gpfs/hpchome/andriiro/.local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 509, in kernel_call
    self.set_args(*args)
  File "/gpfs/hpchome/andriiro/.local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 562, in kernel_set_args
    % (i+1, str(e), advice))
pyopencl.LogicError: when processing argument #3 (1-based): clSetKernelArg failed: invalid arg size
size: 25
Traceback (most recent call last):
  File "measurements.py", line 157, in <module>
    main()
  File "measurements.py", line 135, in main
    measurements.naive_pocl_measurements()
  File "measurements.py", line 58, in naive_pocl_measurements
    results = self._measure(self.naive_pocl)
  File "measurements.py", line 102, in _measure
    obj.all_matches(paterns[i])
  File "/gpfs/hpchome/andriiro/seminar/pattern_matching/Pyopencl/naive/naive_pocl.py", line 51, in all_matches
    search(queue, (self.text_len, ), 256, d_str, d_pat, self.text_len, len(pattern), d_matches)
  File "/gpfs/hpchome/andriiro/.local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 509, in kernel_call
    self.set_args(*args)
  File "/gpfs/hpchome/andriiro/.local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 562, in kernel_set_args
    % (i+1, str(e), advice))
pyopencl.LogicError: when processing argument #3 (1-based): clSetKernelArg failed: invalid arg size
size: 25
Traceback (most recent call last):
  File "measurements.py", line 157, in <module>
    main()
  File "measurements.py", line 135, in main
    measurements.naive_pocl_measurements()
  File "measurements.py", line 58, in naive_pocl_measurements
    results = self._measure(self.naive_pocl)
  File "measurements.py", line 102, in _measure
    obj.all_matches(paterns[i])
  File "/gpfs/hpchome/andriiro/seminar/pattern_matching/Pyopencl/naive/naive_pocl.py", line 51, in all_matches
    search(queue, (self.text_len, ), 256, d_str, d_pat, self.text_len, len(pattern), d_matches)
  File "/gpfs/hpchome/andriiro/.local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 509, in kernel_call
    self.set_args(*args)
  File "/gpfs/hpchome/andriiro/.local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 562, in kernel_set_args
    % (i+1, str(e), advice))
pyopencl.LogicError: when processing argument #3 (1-based): clSetKernelArg failed: invalid arg size
size: 25
Traceback (most recent call last):
  File "measurements.py", line 157, in <module>
    main()
  File "measurements.py", line 135, in main
    measurements.naive_pocl_measurements()
  File "measurements.py", line 58, in naive_pocl_measurements
    results = self._measure(self.naive_pocl)
  File "measurements.py", line 102, in _measure
    obj.all_matches(paterns[i])
  File "/gpfs/hpchome/andriiro/seminar/pattern_matching/Pyopencl/naive/naive_pocl.py", line 51, in all_matches
    search(queue, (self.text_len, ), 256, d_str, d_pat, self.text_len, len(pattern), d_matches)
  File "/gpfs/hpchome/andriiro/.local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 509, in kernel_call
    self.set_args(*args)
  File "/gpfs/hpchome/andriiro/.local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 562, in kernel_set_args
    % (i+1, str(e), advice))
pyopencl.LogicError: when processing argument #3 (1-based): clSetKernelArg failed: invalid arg size
size: 25
Traceback (most recent call last):
  File "measurements.py", line 157, in <module>
    main()
  File "measurements.py", line 135, in main
    measurements.naive_pocl_measurements()
  File "measurements.py", line 58, in naive_pocl_measurements
    results = self._measure(self.naive_pocl)
  File "measurements.py", line 102, in _measure
    obj.all_matches(paterns[i])
  File "/gpfs/hpchome/andriiro/seminar/pattern_matching/Pyopencl/naive/naive_pocl.py", line 51, in all_matches
    search(queue, (self.text_len, ), 256, d_str, d_pat, self.text_len, len(pattern), d_matches)
  File "/gpfs/hpchome/andriiro/.local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 509, in kernel_call
    self.set_args(*args)
  File "/gpfs/hpchome/andriiro/.local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 562, in kernel_set_args
    % (i+1, str(e), advice))
pyopencl.LogicError: when processing argument #3 (1-based): clSetKernelArg failed: invalid arg size
srun: error: stage4: tasks 0-3,6-8: Exited with exit code 1
